# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, upload_to=users.models.user_photos),
        ),
    ]
