# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='photo',
        ),
    ]
