# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180126_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
