# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180127_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='assets/images/user.svg', upload_to=users.models.user_photos),
        ),
    ]
