# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 20:46
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20171119_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
